# Generated by Django 4.0.4 on 2022-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recemail',
            name='msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='msg',
            field=models.TimeField(),
        ),
    ]
