# Generated by Django 4.0.4 on 2022-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='recemail',
            name='msg',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recemail',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='msg',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
