# Generated by Django 4.0.4 on 2022-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0002_alter_recemail_msg_alter_sendemail_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectArea',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectCost',
            field=models.IntegerField(null=True),
        ),
    ]
