# Generated by Django 4.0.4 on 2022-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0002_alter_clientinfo_phone_alter_recemail_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YOE', models.IntegerField(default=0)),
                ('totalProjects', models.IntegerField(default=0)),
                ('totalEmployees', models.IntegerField(default=0)),
                ('totalClients', models.IntegerField(default=0)),
                ('totalPartners', models.IntegerField(default=0)),
                ('totalCities', models.IntegerField(default=0)),
                ('totalArea', models.IntegerField(default=0)),
                ('PAC', models.IntegerField(default=0)),
                ('IAC', models.IntegerField(default=0)),
                ('BAC', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Variables',
            },
        ),
    ]
