# Generated by Django 4.0.4 on 2022-07-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0003_alter_project_projectarea_alter_project_projectcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='clientRequirements',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='plotAddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='projectDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientserviceinfo',
            name='details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectDesc',
            field=models.CharField(max_length=500),
        ),
    ]
