# Generated by Django 4.0.4 on 2022-07-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0003_updatevariables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateVariables',
            new_name='UpdateVariable',
        ),
        migrations.AlterModelOptions(
            name='updatevariable',
            options={'verbose_name': 'Variable'},
        ),
    ]
