# Generated by Django 4.0.4 on 2022-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0004_rename_updatevariables_updatevariable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatevariable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
