# Generated by Django 4.0.4 on 2022-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0005_alter_updatevariable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatevariable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
