# Generated by Django 4.0.4 on 2022-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0006_alter_updatevariable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatevariable',
            name='BACS',
            field=models.FloatField(default=0.0),
        ),
    ]
