# Generated by Django 4.0.4 on 2022-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0007_updatevariable_bacs'),
    ]

    operations = [
        migrations.AddField(
            model_name='recemail',
            name='read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sendemail',
            name='read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
