# Generated by Django 4.0.4 on 2022-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0009_alter_recemail_read_alter_sendemail_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatevariable',
            name='yt1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='updatevariable',
            name='yt2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
